import { existsSync } from 'node:fs';
import { join } from 'node:path';

// Build-time card source: serve the lossless-WebP sibling of a card PNG when
// it exists (generated by npm run cards:webp), otherwise the PNG itself — so
// a freshly rendered card that hasn't been converted yet still displays.
// Runs only in frontmatter at build; the check is against public/ on disk.
// OG images are exempt on purpose: callers pass og_image paths straight
// through, since some link scrapers still refuse WebP.
export function cardSrc(png?: string): string | undefined {
  if (!png || !png.endsWith('.png')) return png;
  const webp = png.replace(/\.png$/, '.webp');
  return existsSync(join(process.cwd(), 'public', webp.slice(1))) ? webp : png;
}
