// Homeland coordinates for each language, for the transmission map: where a
// name-form is plotted. One representative site per language (a chancellery
// capital or heartland city), not a linguistic boundary claim; the place name
// is shown in the node's tooltip. Label offsets (dx/dy in map units, anchor)
// are hand-placed so the Levant and Mesopotamian clusters stay legible.
//
// Coordinates are true lon/lat. The map fits its window to the actual nodes it
// shows (see fitProjection below), so far-flung homelands (Chang'an, say) sit at
// their true place rather than being clamped to a fixed frame; no fake
// coordinates belong here.
import { LAND } from './coastline';
import { RIVERS } from './rivers';
import { REGIONS } from './regions';
import { WATERS } from './waters';

export interface LangGeo {
  lon: number;
  lat: number;
  place: string;
  dx?: number;
  dy?: number;
  anchor?: 'start' | 'middle' | 'end';
}

export const LANG_GEO: Record<string, LangGeo> = {
  pali: { lon: 85.14, lat: 25.61, place: 'Pāṭaliputta', dy: 12 },
  sogdian: { lon: 66.98, lat: 39.65, place: 'Samarkand', dy: -6 },
  egyptian: { lon: 31.25, lat: 29.85, place: 'Memphis', anchor: 'end', dx: -7, dy: 9 },
  demotic: { lon: 30.4, lat: 31.0, place: 'Sais', anchor: 'end', dx: -7, dy: -5 },
  coptic: { lon: 32.65, lat: 25.7, place: 'Thebes' },
  akkadian: { lon: 44.42, lat: 32.54, place: 'Babylon', anchor: 'middle', dx: 0, dy: 14 },
  sumerian: { lon: 45.64, lat: 31.32, place: 'Uruk', dy: 12 },
  elamite: { lon: 48.25, lat: 32.19, place: 'Susa', dx: 8, dy: -3 },
  hittite: { lon: 34.62, lat: 40.02, place: 'Hattusa', dy: -6, anchor: 'middle', dx: 0 },
  ugaritic: { lon: 35.78, lat: 35.6, place: 'Ugarit', anchor: 'end', dx: -7 },
  hurrian: { lon: 40.05, lat: 36.85, place: 'Waššukanni', dy: -6 },
  phoenician: { lon: 35.2, lat: 33.27, place: 'Tyre', anchor: 'end', dx: -7, dy: -2 },
  moabite: { lon: 35.78, lat: 31.5, place: 'Dibon', anchor: 'start', dx: 7, dy: 4 },
  'biblical-hebrew': { lon: 35.23, lat: 31.78, place: 'Jerusalem', dx: 7, dy: 4 },
  'imperial-aramaic': { lon: 36.31, lat: 33.51, place: 'Damascus', dx: 7, dy: 6 },
  syriac: { lon: 38.79, lat: 37.16, place: 'Edessa', dy: -6 },
  'jewish-babylonian-aramaic': { lon: 43.77, lat: 33.36, place: 'Pumbedita', anchor: 'end', dx: -7, dy: -4 },
  'ancient-greek': { lon: 23.73, lat: 37.98, place: 'Athens', anchor: 'end', dx: -7 },
  'byzantine-greek': { lon: 28.98, lat: 41.01, place: 'Constantinople' },
  latin: { lon: 12.49, lat: 41.9, place: 'Rome', dy: -6 },
  'medieval-latin': { lon: 12.49, lat: 41.9, place: 'Rome', dy: 8 },
  'ottoman-turkish': { lon: 29.06, lat: 40.18, place: 'Bursa', dy: -6 },
  etruscan: { lon: 11.76, lat: 42.25, place: 'Tarquinia', anchor: 'end', dx: -7, dy: -4 },
  'mycenaean-greek': { lon: 22.75, lat: 37.73, place: 'Mycenae', anchor: 'end', dx: -7, dy: 8 },
  'old-persian': { lon: 52.89, lat: 29.94, place: 'Persepolis', dy: 10 },
  'middle-persian': { lon: 44.58, lat: 33.1, place: 'Ctesiphon', anchor: 'middle', dx: 0, dy: -7 },
  'classical-persian': { lon: 59.57, lat: 36.5, place: 'Tus, Khurasan' },
  parthian: { lon: 58.4, lat: 37.6, place: 'Nisa', dy: -6 },
  avestan: { lon: 66.9, lat: 36.76, place: 'Bactra', dy: -6 },
  sanskrit: { lon: 77.7, lat: 27.5, place: 'Mathura', anchor: 'end', dx: -7 },
  tamil: { lon: 78.12, lat: 9.93, place: 'Madurai', anchor: 'start', dx: 7, dy: 4 },
  'classical-chinese': { lon: 108.94, lat: 34.27, place: "Chang'an", anchor: 'end', dx: -7 },
  'classical-arabic': { lon: 39.83, lat: 24.47, place: 'The Hejaz' },
  geez: { lon: 38.72, lat: 14.13, place: 'Aksum' },
  lycian: { lon: 29.32, lat: 36.35, place: 'Xanthos', anchor: 'middle', dx: 0, dy: 12 },
  'classical-armenian': { lon: 44.55, lat: 39.95, place: 'Artašat', dy: -6 },
  urartian: { lon: 43.36, lat: 38.49, place: 'Tušpa', anchor: 'end', dx: -7, dy: 4 },
};

// --- Entity locators --------------------------------------------------------
// Where the page's *subject* actually sits, drawn on its own transmission map so
// a reader sees not only who named the thing (the language nodes, in accent) but
// where it is (this geometry, in ink). Coordinates are coarse true lon/lat; only
// the current entity's locator is drawn, so a map never carries more than one.
//
// RENDER STRATEGY BY KIND (the locator taxonomy — TransmissionMap.astro switches
// on `kind`):
//   line   — river: `points` are the course, drawn as a polyline.
//   peaks  — mountains: `points` are peaks, each a triangle (one point = one
//            peak, e.g. Olympus; many = a range).
//   point  — city (a diamond) / civ (a star at the heartland): `points` is one
//            coordinate.
//   area   — region (and FUTURE areal features): `points` are a closed polygon,
//            generated by scripts/generate-region-geo.mjs (the hand-drawn cultural
//            hull clipped to the real land, so coastal edges trace the true coast
//            while inland boundaries stay approximate). Future kinds (desert, plateau, plain, valley,
//            forest/jungle, marsh, lake) reuse this hull and are told apart by a
//            MONOCHROME INK FILL PATTERN, never by color: stipple = desert,
//            horizontal hatch = plateau, scattered tree-dots = forest, short
//            ticks = marsh, even wash = plain, wave-lines = lake. To add one:
//            extend the kind union, add an SVG <pattern> + fill class, list it in
//            the `area` branch. Seas stay unlocated (the coastline already shows
//            the water; a label would be the move if ever wanted).
//   range  — nomadic confederations: `points` are a hull of the attested roaming
//            envelope (generated alongside the region hulls), drawn as a DASHED
//            OPEN OUTLINE with no fill: "they moved through here," deliberately
//            unlike a region's solid claim and a civ's heartland star.
//   sea    — `points` frame the water for window-fitting; `rings`, where the
//            50m land data resolves the basin (generated: hull minus land, holes
//            = islands), are the water itself, filled with a DIAGONAL HATCH on
//            both maps. Straits and lakes with no `rings` keep the open ring at
//            the centroid.
export interface EntityGeo {
  kind: 'river' | 'mountains' | 'region' | 'city' | 'civ' | 'sea' | 'range';
  label: string;
  points: [number, number][];
  /** Sea water polygons (MultiPolygon rings, holes = islands); hatch-filled. */
  rings?: [number, number][][][];
}

export const ENTITY_GEO: Record<string, EntityGeo> = {
  // River courses are accurate (Natural Earth 10m, baked into rivers.ts); the
  // coastline stays stylized but a river traces its true bed.
  nile: { kind: 'river', label: 'the Nile', points: RIVERS.nile },
  tigris: { kind: 'river', label: 'the Tigris', points: RIVERS.tigris },
  euphrates: { kind: 'river', label: 'the Euphrates', points: RIVERS.euphrates },
  jordan: { kind: 'river', label: 'the Jordan', points: RIVERS.jordan },
  po: { kind: 'river', label: 'the Po', points: RIVERS.po },
  tiber: { kind: 'river', label: 'the Tiber', points: RIVERS.tiber },
  indus: { kind: 'river', label: 'the Indus', points: RIVERS.indus },
  ganges: { kind: 'river', label: 'the Ganges', points: RIVERS.ganges },
  yamuna: { kind: 'river', label: 'the Yamuna', points: RIVERS.yamuna },
  guadalquivir: { kind: 'river', label: 'the Guadalquivir', points: RIVERS.guadalquivir },
  halys: { kind: 'river', label: 'the Halys', points: [[38.3, 39.7], [37.0, 39.9], [35.6, 39.4], [34.9, 39.4], [34.6, 40.1], [35.2, 40.7], [35.95, 41.3], [36.0, 41.7]] },
  oxus: { kind: 'river', label: 'the Oxus', points: [[71.5, 37.0], [68.5, 37.1], [65.5, 37.4], [63.5, 38.4], [61.8, 39.8], [60.2, 41.2], [59.3, 42.4]] },
  jaxartes: { kind: 'river', label: 'the Jaxartes', points: [[70.0, 40.3], [68.5, 40.5], [66.5, 41.6], [64.5, 43.2], [62.5, 44.6], [61.2, 45.9]] },
  himalayas: { kind: 'mountains', label: 'the Himalayas', points: [[74.6, 35.2], [76.5, 34.5], [78.5, 33.0], [80.5, 30.8], [81.6, 30.3], [83.0, 29.2], [84.5, 28.6], [86.9, 27.9], [88.2, 27.7], [90.3, 28.0], [92.5, 28.0], [95.0, 29.1]] },
  olympus: { kind: 'mountains', label: 'Olympus', points: [[22.35, 40.09]] },
  lebanon: { kind: 'mountains', label: 'Mount Lebanon', points: [[36.0, 34.45], [36.07, 34.30], [35.95, 34.05], [35.85, 33.85], [35.75, 33.6]] },
  ararat: { kind: 'mountains', label: 'Ararat', points: [[44.30, 39.70]] },
  caucasus: { kind: 'mountains', label: 'the Caucasus', points: [[40.0, 43.5], [41.5, 43.4], [43.0, 42.9], [44.5, 42.6], [45.8, 42.5], [47.3, 41.6]] },
  taurus: { kind: 'mountains', label: 'the Taurus', points: [[29.7, 37.0], [31.5, 37.1], [33.0, 37.3], [34.5, 37.6], [35.8, 37.8], [37.2, 38.0]] },
  'hindu-kush': { kind: 'mountains', label: 'the Hindu Kush', points: [[67.0, 36.3], [68.5, 36.0], [70.0, 35.6], [71.3, 35.7], [72.5, 36.1]] },

  // Seas and straits: extent points that frame the water (the coastline the
  // window catches IS the picture); a single point marks a strait or lake.
  // The locator draws an open ring at the centroid rather than a solid mark,
  // since the subject is the space between the coasts.
  mediterranean: { kind: 'sea', label: 'the Mediterranean', points: [[-4, 37], [15, 44], [35, 31]], rings: WATERS.mediterranean },
  aegean: { kind: 'sea', label: 'the Aegean', points: [[23.5, 35.5], [27.5, 40.5]], rings: WATERS.aegean },
  adriatic: { kind: 'sea', label: 'the Adriatic', points: [[12.5, 44.5], [19.5, 40.5]], rings: WATERS.adriatic },
  'ionian-sea': { kind: 'sea', label: 'the Ionian Sea', points: [[16, 36], [21, 39.5]], rings: WATERS['ionian-sea'] },
  'black-sea': { kind: 'sea', label: 'the Black Sea', points: [[28.5, 43.5], [41.5, 42], [33, 46.5]], rings: WATERS['black-sea'] },
  'caspian-sea': { kind: 'sea', label: 'the Caspian', points: [[49, 41], [54, 45.5], [51, 38]], rings: WATERS['caspian-sea'] },
  'red-sea': { kind: 'sea', label: 'the Red Sea', points: [[33, 27.5], [42, 15]], rings: WATERS['red-sea'] },
  'persian-gulf': { kind: 'sea', label: 'the Persian Gulf', points: [[48.5, 29.5], [56, 26]], rings: WATERS['persian-gulf'] },
  marmara: { kind: 'sea', label: 'the Sea of Marmara', points: [[27.2, 40.5], [29.5, 40.8]], rings: WATERS.marmara },
  'dead-sea': { kind: 'sea', label: 'the Dead Sea', points: [[35.5, 31.5]] },
  bosporus: { kind: 'sea', label: 'the Bosporus', points: [[29.05, 41.15]] },
  hellespont: { kind: 'sea', label: 'the Hellespont', points: [[26.4, 40.2]] },

  // Regions: coast-accurate outlines baked into regions.ts (each cultural hull
  // clipped to real land; coastal edges trace the true coast, inland stay coarse).
  deccan: { kind: 'region', label: 'the Deccan', points: REGIONS.deccan },
  maghreb: { kind: 'region', label: 'the Maghreb', points: REGIONS.maghreb },
  khurasan: { kind: 'region', label: 'Khurasan', points: REGIONS.khurasan },
  transoxiana: { kind: 'region', label: 'Transoxiana', points: REGIONS.transoxiana },
  anatolia: { kind: 'region', label: 'Anatolia', points: REGIONS.anatolia },
  canaan: { kind: 'region', label: 'Canaan', points: REGIONS.canaan },
  italia: { kind: 'region', label: 'Italia', points: REGIONS.italia },
  latium: { kind: 'region', label: 'Latium', points: REGIONS.latium },
  macedonia: { kind: 'region', label: 'Macedonia', points: REGIONS.macedonia },
  'magna-graecia': { kind: 'region', label: 'Magna Graecia', points: REGIONS["magna-graecia"] },
  mesopotamia: { kind: 'region', label: 'Mesopotamia', points: REGIONS.mesopotamia },
  sicily: { kind: 'region', label: 'Sicily', points: REGIONS.sicily },
  syria: { kind: 'region', label: 'Syria', points: REGIONS.syria },
  phrygia: { kind: 'region', label: 'Phrygia', points: REGIONS.phrygia },
  lydia: { kind: 'region', label: 'Lydia', points: REGIONS.lydia },
  ionia: { kind: 'region', label: 'Ionia', points: REGIONS.ionia },
  cappadocia: { kind: 'region', label: 'Cappadocia', points: REGIONS.cappadocia },
  cilicia: { kind: 'region', label: 'Cilicia', points: REGIONS.cilicia },
  lycia: { kind: 'region', label: 'Lycia', points: REGIONS.lycia },
  philistia: { kind: 'region', label: 'Philistia', points: REGIONS.philistia },
  sogdiana: { kind: 'region', label: 'Sogdiana', points: REGIONS.sogdiana },
  iran: { kind: 'region', label: 'Iran', points: REGIONS.iran },
  gandhara: { kind: 'region', label: 'Gandhāra', points: REGIONS.gandhara },
  punjab: { kind: 'region', label: 'the Punjab', points: REGIONS.punjab },
  sindh: { kind: 'region', label: 'Sindh', points: REGIONS.sindh },

  // Cities (a point at the site).
  alexandria: { kind: 'city', label: 'Alexandria', points: [[29.92, 31.20]] },
  pataliputra: { kind: 'city', label: 'Pāṭaliputra', points: [[85.14, 25.61]] },
  taxila: { kind: 'city', label: 'Taxila', points: [[72.82, 33.74]] },
  bactra: { kind: 'city', label: 'Bactra', points: [[66.90, 36.76]] },
  'chang-an': { kind: 'city', label: "Chang'an", points: [[108.86, 34.30]] },
  athens: { kind: 'city', label: 'Athens', points: [[23.73, 37.98]] },
  babylon: { kind: 'city', label: 'Babylon', points: [[44.42, 32.54]] },
  baghdad: { kind: 'city', label: 'Baghdad', points: [[44.36, 33.31]] },
  cairo: { kind: 'city', label: 'Cairo', points: [[31.24, 30.05]] },
  cordoba: { kind: 'city', label: 'Córdoba', points: [[-4.78, 37.88]] },
  seville: { kind: 'city', label: 'Seville', points: [[-5.99, 37.39]] },
  toledo: { kind: 'city', label: 'Toledo', points: [[-4.02, 39.86]] },
  granada: { kind: 'city', label: 'Granada', points: [[-3.60, 37.18]] },
  kairouan: { kind: 'city', label: 'Kairouan', points: [[10.10, 35.68]] },
  fez: { kind: 'city', label: 'Fez', points: [[-4.98, 34.06]] },
  merv: { kind: 'city', label: 'Merv', points: [[61.83, 37.66]] },
  konya: { kind: 'city', label: 'Konya', points: [[32.49, 37.87]] },
  nicaea: { kind: 'city', label: 'Nicaea', points: [[29.72, 40.43]] },
  bursa: { kind: 'city', label: 'Bursa', points: [[29.06, 40.18]] },
  edirne: { kind: 'city', label: 'Edirne', points: [[26.56, 41.68]] },
  nishapur: { kind: 'city', label: 'Nishapur', points: [[58.80, 36.21]] },
  bukhara: { kind: 'city', label: 'Bukhara', points: [[64.42, 39.77]] },
  samarkand: { kind: 'city', label: 'Samarkand', points: [[66.96, 39.65]] },
  mecca: { kind: 'city', label: 'Mecca', points: [[39.83, 21.42]] },
  medina: { kind: 'city', label: 'Medina', points: [[39.61, 24.47]] },
  byzantium: { kind: 'city', label: 'Byzantium', points: [[28.98, 41.01]] },
  corinth: { kind: 'city', label: 'Corinth', points: [[22.88, 37.91]] },
  damascus: { kind: 'city', label: 'Damascus', points: [[36.31, 33.51]] },
  ephesus: { kind: 'city', label: 'Ephesus', points: [[27.34, 37.94]] },
  jerusalem: { kind: 'city', label: 'Jerusalem', points: [[35.23, 31.78]] },
  knossos: { kind: 'city', label: 'Knossos', points: [[25.16, 35.30]] },
  memphis: { kind: 'city', label: 'Memphis', points: [[31.25, 29.85]] },
  miletus: { kind: 'city', label: 'Miletus', points: [[27.28, 37.53]] },
  mycenae: { kind: 'city', label: 'Mycenae', points: [[22.76, 37.73]] },
  neapolis: { kind: 'city', label: 'Neapolis', points: [[14.27, 40.84]] },
  nineveh: { kind: 'city', label: 'Nineveh', points: [[43.15, 36.36]] },
  pella: { kind: 'city', label: 'Pella', points: [[22.52, 40.76]] },
  persepolis: { kind: 'city', label: 'Persepolis', points: [[52.89, 29.94]] },
  sidon: { kind: 'city', label: 'Sidon', points: [[35.37, 33.56]] },
  sparta: { kind: 'city', label: 'Sparta', points: [[22.43, 37.07]] },
  susa: { kind: 'city', label: 'Susa', points: [[48.25, 32.19]] },
  syracuse: { kind: 'city', label: 'Syracuse', points: [[15.29, 37.07]] },
  tarentum: { kind: 'city', label: 'Tarentum', points: [[17.24, 40.47]] },
  tarquinia: { kind: 'city', label: 'Tarquinia', points: [[11.76, 42.25]] },
  thebes: { kind: 'city', label: 'Thebes', points: [[23.32, 38.32]] },
  troy: { kind: 'city', label: 'Troy', points: [[26.24, 39.96]] },
  tyre: { kind: 'city', label: 'Tyre', points: [[35.20, 33.27]] },
  ur: { kind: 'city', label: 'Ur', points: [[46.10, 30.96]] },
  uruk: { kind: 'city', label: 'Uruk', points: [[45.64, 31.32]] },
  veii: { kind: 'city', label: 'Veii', points: [[12.39, 42.03]] },

  // Civilizations (a star at the heartland / seat — not a claim of borders).
  akkad: { kind: 'civ', label: 'Akkad', points: [[44.40, 32.90]] },
  assyria: { kind: 'civ', label: 'Assyria', points: [[43.26, 35.46]] },
  byzantines: { kind: 'civ', label: 'The Byzantines', points: [[28.98, 41.01]] },
  caliphate: { kind: 'civ', label: 'The Caliphate', points: [[44.36, 33.31]] },
  'al-andalus': { kind: 'civ', label: 'Al-Andalus', points: [[-4.78, 37.88]] },
  ottomans: { kind: 'civ', label: 'The Ottomans', points: [[29.06, 40.18]] },
  seljuks: { kind: 'civ', label: 'The Seljuks', points: [[32.49, 37.87]] },
  'crusader-states': { kind: 'civ', label: 'The Crusader States', points: [[35.07, 32.93]] },
  babylonia: { kind: 'civ', label: 'Babylonia', points: [[44.42, 32.54]] },
  bactria: { kind: 'civ', label: 'Bactria', points: [[66.90, 36.76]] },
  carthage: { kind: 'civ', label: 'Carthage', points: [[10.32, 36.85]] },
  china: { kind: 'civ', label: 'China', points: [[112.40, 34.60]] },
  dilmun: { kind: 'civ', label: 'Dilmun', points: [[50.52, 26.23]] },
  egypt: { kind: 'civ', label: 'Egypt', points: [[31.25, 29.85]] },
  elam: { kind: 'civ', label: 'Elam', points: [[48.25, 32.19]] },
  magan: { kind: 'civ', label: 'Magan', points: [[57.55, 23.35]] },
  meluhha: { kind: 'civ', label: 'Meluhha', points: [[68.14, 27.33]] },
  etruscans: { kind: 'civ', label: 'Etruria', points: [[11.70, 42.50]] },
  greece: { kind: 'civ', label: 'Greece', points: [[23.50, 38.30]] },
  hittites: { kind: 'civ', label: 'Ḫatti', points: [[34.62, 40.02]] },
  india: { kind: 'civ', label: 'India', points: [[79.00, 26.00]] },
  israel: { kind: 'civ', label: 'Israel', points: [[35.20, 32.28]] },
  judah: { kind: 'civ', label: 'Judah', points: [[35.23, 31.78]] },
  macedon: { kind: 'civ', label: 'Macedon', points: [[22.52, 40.76]] },
  'minoan-crete': { kind: 'civ', label: 'Minoan Crete', points: [[25.16, 35.30]] },
  mitanni: { kind: 'civ', label: 'Mitanni', points: [[40.00, 36.85]] },
  parthia: { kind: 'civ', label: 'Parthia', points: [[58.40, 37.60]] },
  persia: { kind: 'civ', label: 'Persia', points: [[53.00, 30.00]] },
  phoenicia: { kind: 'civ', label: 'Phoenicia', points: [[35.40, 33.90]] },
  rome: { kind: 'civ', label: 'Rome', points: [[12.50, 41.90]] },
  sumer: { kind: 'civ', label: 'Sumer', points: [[45.80, 31.30]] },
  media: { kind: 'civ', label: 'Media', points: [[48.51, 34.80]] },
  armenia: { kind: 'civ', label: 'Armenia', points: [[44.50, 40.00]] },
  urartu: { kind: 'civ', label: 'Urartu', points: [[43.36, 38.49]] },

  // Steppe peoples: a star at a representative seat, not a homeland border (nomads).
  scythia: { kind: 'range', label: 'Scythia', points: REGIONS.scythia },
  cimmerians: { kind: 'range', label: 'Cimmeria', points: REGIONS.cimmerians },
  xiongnu: { kind: 'range', label: 'Xiongnu', points: REGIONS.xiongnu },
  yuezhi: { kind: 'range', label: 'Yuezhi', points: REGIONS.yuezhi },
  romani: { kind: 'range', label: 'Romani range', points: REGIONS.romani },
};

// --- Per-map projection -----------------------------------------------------
// The map window is computed from the nodes it must show, then everything (the
// coastline included) is projected into it. This is the fix for the old fixed
// scale: a Chang'an node no longer falls off the edge of a Near-East window;
// instead the window grows to include China. The projection is plain
// equirectangular (x ∝ lon, y ∝ -lat), matching the look of the old baked maps.

export interface Bounds {
  lonMin: number;
  lonMax: number;
  latMin: number;
  latMax: number;
}
export interface Projection {
  project(lon: number, lat: number): { x: number; y: number };
  bounds: Bounds;
  viewBox: string;
  width: number;
  height: number;
}

// Every map is the same width in user units, so labels (12.5px) and node dots
// (r=3.2) read consistently whatever the geographic span; only the height and
// the degrees-per-pixel scale vary per map.
const VIEW_W = 800;
const PAD_FRAC = 0.14; // breathing room around the outermost nodes, per side
const PAD_MIN = 3; // ...but at least this many degrees, for tight clusters
const MIN_LON_SPAN = 20; // a one- or two-city map should not zoom in absurdly
const MAX_ASPECT = 0.82; // cap height/width; widen the lon window if too tall
const MIN_ASPECT = 0.42; // floor height/width; add vertical context if too flat

/** Fit an equirectangular window around the given coordinates and return a
    projector into a VIEW_W-wide pixel space. `minLonSpan` is the floor on the
    window's width: a sparse map (one or two names, clustered) passes a larger
    floor than the default so enough of the surrounding coast and sea shows for a
    reader to tell where on earth the place is, rather than zooming in on a lone
    node with no recognizable context. */
export function fitProjection(
  geos: Array<{ lon: number; lat: number }>,
  minLonSpan: number = MIN_LON_SPAN
): Projection {
  let lonMin = Infinity;
  let lonMax = -Infinity;
  let latMin = Infinity;
  let latMax = -Infinity;
  for (const g of geos) {
    lonMin = Math.min(lonMin, g.lon);
    lonMax = Math.max(lonMax, g.lon);
    latMin = Math.min(latMin, g.lat);
    latMax = Math.max(latMax, g.lat);
  }
  if (!Number.isFinite(lonMin)) {
    // No located nodes: fall back to a Mediterranean / Near-East window.
    lonMin = 8; lonMax = 60; latMin = 12; latMax = 45;
  }
  const padLon = Math.max((lonMax - lonMin) * PAD_FRAC, PAD_MIN);
  const padLat = Math.max((latMax - latMin) * PAD_FRAC, PAD_MIN);
  lonMin -= padLon; lonMax += padLon;
  latMin -= padLat; latMax += padLat;

  let lonSpan = lonMax - lonMin;
  if (lonSpan < minLonSpan) {
    const grow = (minLonSpan - lonSpan) / 2;
    lonMin -= grow; lonMax += grow;
    lonSpan = minLonSpan;
  }
  let latSpan = latMax - latMin;
  if (latSpan > MAX_ASPECT * lonSpan) {
    // Too tall: widen the longitude window symmetrically to cap the aspect.
    const target = latSpan / MAX_ASPECT;
    const grow = (target - lonSpan) / 2;
    lonMin -= grow; lonMax += grow;
    lonSpan = target;
  } else if (latSpan < MIN_ASPECT * lonSpan) {
    // Too flat (a Rome-to-China strip): add latitude context above and below
    // so the map reads as a map, not a band. Nodes keep their true positions.
    const target = MIN_ASPECT * lonSpan;
    const grow = (target - latSpan) / 2;
    latMin -= grow; latMax += grow;
    latSpan = target;
  }

  const scale = VIEW_W / lonSpan;
  const width = VIEW_W;
  const height = latSpan * scale;
  const bounds = { lonMin, lonMax, latMin, latMax };
  const project = (lon: number, lat: number) => ({
    x: (lon - lonMin) * scale,
    y: (latMax - lat) * scale,
  });
  return { project, bounds, viewBox: `0 0 ${width.toFixed(1)} ${height.toFixed(1)}`, width, height };
}

// Sutherland-Hodgman clip of a lon/lat ring to the map's bounds, so each map's
// SVG carries only the coastline it actually shows.
function clipRing(ring: ReadonlyArray<readonly [number, number]>, b: Bounds) {
  const params: Array<[0 | 1, number, (p: readonly [number, number]) => boolean]> = [
    [0, b.lonMin, (p) => p[0] >= b.lonMin],
    [0, b.lonMax, (p) => p[0] <= b.lonMax],
    [1, b.latMin, (p) => p[1] >= b.latMin],
    [1, b.latMax, (p) => p[1] <= b.latMax],
  ];
  const intersect = (
    a: readonly [number, number],
    c: readonly [number, number],
    axis: 0 | 1,
    value: number
  ): [number, number] => {
    const t = (value - a[axis]) / (c[axis] - a[axis]);
    return axis === 0
      ? [value, a[1] + t * (c[1] - a[1])]
      : [a[0] + t * (c[0] - a[0]), value];
  };
  let out: Array<readonly [number, number]> = ring as Array<readonly [number, number]>;
  for (const [axis, value, inside] of params) {
    const next: Array<readonly [number, number]> = [];
    for (let i = 0; i < out.length; i++) {
      const cur = out[i];
      const prev = out[(i + out.length - 1) % out.length];
      if (inside(cur)) {
        if (!inside(prev)) next.push(intersect(prev, cur, axis, value));
        next.push(cur);
      } else if (inside(prev)) {
        next.push(intersect(prev, cur, axis, value));
      }
    }
    out = next;
    if (out.length === 0) return null;
  }
  return out;
}

/** Project the baked land rings into the given window as one SVG path string. */
// Douglas-Peucker on a projected (pixel-space) ring. Run per map AFTER projecting,
// so the coastline carries a constant level of on-screen detail at every zoom: a
// wide map drops fine geographic detail (staying light and angular, as the maps look
// today), while a zoomed-in map keeps it, since the same features now span more pixels
// and fewer of their vertices fall under the pixel tolerance. Iterative (an explicit
// stack) so a long clipped coastline can't overflow the call stack.
const COAST_PIXEL_TOLERANCE = 1.1;
function simplifyPixels(pts: ReadonlyArray<{ x: number; y: number }>, eps: number): Array<{ x: number; y: number }> {
  const n = pts.length;
  if (n < 3) return pts.slice();
  const keep = new Uint8Array(n);
  keep[0] = 1;
  keep[n - 1] = 1;
  const stack: Array<[number, number]> = [[0, n - 1]];
  const eps2 = eps * eps;
  while (stack.length) {
    const [first, last] = stack.pop()!;
    if (last - first < 2) continue;
    const a = pts[first];
    const b = pts[last];
    const dx = b.x - a.x;
    const dy = b.y - a.y;
    const len2 = dx * dx + dy * dy;
    let dmax = -1;
    let idx = -1;
    for (let i = first + 1; i < last; i++) {
      const p = pts[i];
      const cross = (p.x - a.x) * dy - (p.y - a.y) * dx;
      const d2 = len2 === 0 ? (p.x - a.x) ** 2 + (p.y - a.y) ** 2 : (cross * cross) / len2;
      if (d2 > dmax) {
        dmax = d2;
        idx = i;
      }
    }
    if (dmax > eps2 && idx > first) {
      keep[idx] = 1;
      stack.push([first, idx], [idx, last]);
    }
  }
  const out: Array<{ x: number; y: number }> = [];
  for (let i = 0; i < n; i++) if (keep[i]) out.push(pts[i]);
  return out;
}

export function landPath(proj: Projection): string {
  const parts: string[] = [];
  for (const ring of LAND) {
    const clipped = clipRing(ring, proj.bounds);
    if (!clipped || clipped.length < 4) continue;
    const projected = clipped.map(([lon, lat]) => proj.project(lon, lat));
    const thinned = simplifyPixels(projected, COAST_PIXEL_TOLERANCE);
    if (thinned.length < 3) continue;
    const d = thinned.map((p) => `${p.x.toFixed(1)},${p.y.toFixed(1)}`).join('L');
    parts.push(`M${d}Z`);
  }
  return parts.join('');
}
